"""empty message

Revision ID: bce7b532ed16
Revises: 47026262eb6b
Create Date: 2022-03-04 20:14:22.930563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce7b532ed16'
down_revision = '47026262eb6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user_profiles', ['password'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
